### ISSUE TITLE
Go's for range operator -> lua generic for loop

### ISSUE THREAD

**Issue by glycerine** [go-interpreter/gi#8]
Go's range operator operates on slices, maps, and arrays. Lua's for-do loop is very similar, but we need to write examples for tests that ensure/establish a consistent mapping. (update, not necessarily a consistent ordering of keys, that Go does not guarantee. Rather, I mean a correct semantic translation from Go to Lua).

For example, given a slice 

~~~
a := []int{1,2,3}
~~~

then the Go code
~~~
for k, v:= range a {
  ...
}
~~~
maps pretty directly to the Lua generic for loop 

~~~
for k, v in pairs(a) do 
  ...
end
~~~

reference https://www.lua.org/manual/5.3/manual.html#3.3.5

**Comment by sbinet** [comment]
That may be true for a range over a slice, array or string (although for strings there's the possibly different handling of Unicode) but I don't think this will hold for maps, especially the randomized iteration order :)

**Comment by glycerine** [comment]
@sbinet An excellent point about strings needing unicode character special treatment. Must handle that correctly.

The randomized map order of Go actually seems helpful here, since the Lua translation can then iterate in any order and still be correct. Or were you thinking of something else?

**Comment by sbinet** [comment]
that and the fact that all elements have to be iterated once even when one removes one of them during the iteration.
not saying that can't be done of course :)

**Comment by glycerine** [comment]
Another excellent point. Thanks Sebastien.

Go works around deletion in the middle of map iteration, presumably by copying the key list prior to to the start of the iteration. 

I just checked. It looks like Lua allows the same deletion in the middle of iteration.  Stackoverflow discussion [1], `Mud` claims this show work as we seen below.

> For non-array tables, you iterate using next or pairs (which is implemented in terms of next) and set items you want removed to nil.

~~~
> t={}; t.a=1; t.b=2; t.c = 3; for k, v in pairs(t) do print("key:"..k.." val:"..v); t.a=nil; t.c=nil;  end
key:b val:2
> t={}; t.a=1; t.b=2; t.c = 3; for k, v in pairs(t) do print("key:"..k.." val:"..v); t.a=nil;  end
key:b val:2
key:c val:3
> t={}; t.a=1; t.b=2; t.c = 3; for k, v in pairs(t) do print("key:"..k.." val:"..v);  end
key:b val:2
key:a val:1
key:c val:3
> t={}; t.a=1; t.b=2; t.c = 3; for k, v in pairs(t) do print("key:"..k.." val:"..v); t.b=nil; t.c=nil;  end
key:b val:2
key:a val:1
>
~~~

[1] https://stackoverflow.com/questions/12394841/safely-remove-items-from-an-array-table-while-iterating

**Comment by glycerine** [comment]
for loops are done for slices, and I've opened a separate ticket for the unicode chunking over strings, #13 . closing this out.
